### ISSUE TITLE
write permission in validator PVC

### ISSUE THREAD

**Issue by Lars44871934** [fangpenlin/eth2-validator-helm#2]
Thanks for sharing the helm chart! I did install the chart on a Linode k8s cluster. The `openethereum` and `beacon` pods spin up alright. But the `validator` pod runs into `CrashLoopBackOff` due to a permission problem. The two secrets exist. Three PVCs are Bound and RWO.

```
CRIT Failed to start validator client reason: Unable to open or create validator definitions: UnableToWriteFile(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```
Do I need to modify the [`securityContext`](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)? I would appreciate your advice how to debug further.

**Comment by fangpenlin** [comment]
Hi @Lars44871934,

I would recommend open a shell in your pod to run commands to see what's going on. Say your pod name is `my-validator-1234`, then you can run kubectl command like this

```bash
kubectl exec -it my-validator-1234 /bin/bash
```

This will open a shell inside the pod's container. In that way, you can run command like

```bash
ls -al /path/to/mount-folder
```

to find out the permission settings of that folder.

And yeah, I think it's highly possible the error you encountered has something to do with `securityContext`. We are running as user 1000 for the mounted volume filesystem by default

https://github.com/fangpenlin/eth2-validator-helm/blob/ecfa7b636aa9071b179d4bbc39356939b325a8e6/values.yaml#L247-L252

You can check and see whether your 1000 user in that container has permission to access the mounted volume.

**Comment by Lars44871934** [comment]
First, I modified `storageClass` and `UID` in `values.yaml` for [my specific host system](https://github.com/Lars44871934/eth2-validator-helm/commit/e348eede204c575613d47cfb81f9d0ff9ce0b19a). I then [modified the chart](https://github.com/Lars44871934/eth2-validator-helm/blob/master/templates/validator-statefulset.yaml#L47) in order to prevent crash/restart of the pod (`CrashLoopBackOff`). That allowed me to get inside the pod.
```
/var/data/secrets
```
The secrets folder is missing. The other folders have `rwx` permissions for my user `500`.

**Comment by fangpenlin** [comment]
Hmm, that sounds pretty odd. Can you please run

```bash
kubectl get secret
```

and see if `eth2-validator-keystore` and `eth2-validator-password` are there as described [here](https://github.com/fangpenlin/eth2-validator-helm#install-validator-keystore-and-password)?

And I never use Kubernetes running on Linode, not sure if there's any difference between other cloud provider's K8S service. Can you also try to create a new simple deployment with a secret attached as volume, and see if secret volume mounting works?

**Comment by Lars44871934** [comment]
@fangpenlin I changed `openethereum` to `geth` and now the chart works. https://github.com/Lars44871934/eth2-validator-helm Sorry for this issue. And thanks for sharing your chart and the support.
