### ISSUE TITLE
Ingresses

### ISSUE THREAD

**Issue by vanthome** [fangpenlin/eth2-validator-helm#3]
Hi, thanks for this great chart! A question about the Geth RCP port 8545/TPC and 8546/TCP. Those are defined as services but they need to be exposed to the outside, right? In that case, the chart would need to run on a node that has a public IP. Have you thought about adding ingresses for these as well?
BG

**Comment by Lars44871934** [comment]
I think port 8545 does not need to be exposed outside the Kubernetes cluster. The ETH 2 becon node access the ETH 1 client on `http://localhost:8545`. 

![ethcluster-1024x522](https://user-images.githubusercontent.com/85891069/122719692-d9f6d580-d26e-11eb-835c-9b18ba67581c.png)

**Comment by fangpenlin** [comment]
It's totally up to user to decide whether they want to expose specific service or not to the outside world. By default, the service type is `ClusterIP`, thus the service is only accessible from within the cluster:

https://github.com/fangpenlin/eth2-validator-helm/blob/ecfa7b636aa9071b179d4bbc39356939b325a8e6/values.yaml#L56

You can change the service type to `LoadBalancer`, it depends on which cloud provider you are using. Say if you are using GKE (Google Kubernetes Engine), a corresponding GCP LoadBalancer will be created and a public IP will be assigned to that LoadBalancer unless there's other configuration stops that from happening.

**Comment by vanthome** [comment]
thx
